### ISSUE TITLE
Use different handlers for different methods but same uri

### ISSUE THREAD

**Issue by wneirynck** [metosin/kekkonen#31]
It would really be useful if we could assign different handlers to different methods (http) in the same uri.  For instance:

```
(p/defnk ^:query show-thing
  {:path "/thing"}
  []
  ...)

(p/defnk ^:command update-thing
  {:path "/thing"}
  []
  ...)
```
This way we could do a more REST-like approach that uses the same uri (e.g. "/thing") but different methods for different actions (the same goes for the http-api, with PUT, DELETE, etc...).  Or is it already possible, and if so, how?

**Comment by ikitommi** [comment]
hi.

currently that is not possible to do that. Idea of Kekkonen is abstract away the http - to enable writing apis is idiomatic clojure and to easily enable same apis over web-sockets & message queues. So, overwriting paths at `kekkonen.core` is something that will most likely not happen. It could be made to work, but would be a step away from the current simplicity.

At the http-adapter-level, we could do that. We already have the `:kekkonen.ring/method`, which allow to override the http method. there could be `:kekkonen.ring/path` which could be used. BUT - this would work only with the http. 

You really can't make "perfect" REST apis with Kekkonen, by design.

**Comment by wneirynck** [comment]
Yep, I already though of that myself.  It is indeed a little bit against the philosophy of the Kekkonen library, which is about abstraction.  But extending the http adapter could take us a long way, see issue #32
