### ISSUE TITLE
Clout-style handling

### ISSUE THREAD

**Issue by wneirynck** [metosin/kekkonen#32]
It should be possible to use clout uri matching for handlers:

`(p/defnk ^:query show
  {:path "show/:id"}
  [[:data id :- s/Int]]
  (println "The id is" id)
  (success "ok"))`

This should be reachable using e.g. "/api/show/:id" style urls, where the :id is automatically mapped to the id parameter.  This would also be reflected in the swagger json document.

**Comment by ikitommi** [comment]
Hi. And thanks for the thoughts. See the [previous answer](https://github.com/metosin/kekkonen/issues/31#issuecomment-219055190). This _could_ be added to http-adapter level, but using this would complects the apis - client's need to start splitting their input data into two things:

1) path-parameters, which need to be string concatenated into the path
2) the rest of the parameters

currently, all the calls in the client-side look like:

```clj
(cqrs/query :api.ipa/beer {:id 123, :pull [:id :size [:orgin :country]]})
```

, which is already, as simple as it gets?

Having one path-parameter also raises question, should there be full support for path parameters, like `/users/67/orders/23/subthingie/1`. Would make the router much more complex (most web libs use linear routing scan due to this, which is O(n), while Kekkonen routing is O(1)).

Best would be to make the http-adapter extendable, so everyone could write these addons easily. Could do this, but not the top priority now.

How does this sound?

**Comment by wneirynck** [comment]
Agreed.  I realise it is very http-specific.  These are things we encounter because we're trying to adapt an existing interface to use kekkonen.  It would indeed be a good thing if we could extend the http adapter.

**Comment by wneirynck** [comment]
Closing this because it is not matching Kekkonen philosophy
